"""
Halloween items dataset for item generation.
Contains a comprehensive list of Halloween items with categories, descriptions, and price ranges.
"""

# Halloween items dataset - approximately 50 items across different categories
HALLOWEEN_ITEMS = [
    # Costumes
    {
        "name": "Vampire Costume",
        "category": "costume",
        "description": "Classic vampire costume with cape, fangs, and elegant gothic attire",
        "min_price": 25,
        "max_price": 100,
    },
    {
        "name": "Werewolf Costume",
        "category": "costume",
        "description": "Realistic werewolf costume with fur, fangs, and claws",
        "min_price": 40,
        "max_price": 120,
    },
    {
        "name": "Ghost Costume",
        "category": "costume",
        "description": "Classic white ghost costume with ethereal flowing fabric",
        "min_price": 20,
        "max_price": 60,
    },
    {
        "name": "Zombie Bride Costume",
        "category": "costume",
        "description": "Tattered wedding dress with zombie makeup and accessories",
        "min_price": 35,
        "max_price": 90,
    },
    {
        "name": "Skeleton Costume",
        "category": "costume",
        "description": "Full-body skeleton jumpsuit with bone details",
        "min_price": 25,
        "max_price": 70,
    },
    {
        "name": "Witch Costume",
        "category": "costume",
        "description": "Classic witch costume with hat, dress, and broomstick",
        "min_price": 30,
        "max_price": 85,
    },
    {
        "name": "Frankenstein's Monster Costume",
        "category": "costume",
        "description": "Green-skinned monster costume with neck bolts and stitches",
        "min_price": 35,
        "max_price": 95,
    },
    {
        "name": "Mummy Costume",
        "category": "costume",
        "description": "Wrapped bandage costume with ancient Egyptian details",
        "min_price": 30,
        "max_price": 75,
    },
    {
        "name": "Grim Reaper Costume",
        "category": "costume",
        "description": "Hooded black robe with scythe and skeletal features",
        "min_price": 40,
        "max_price": 90,
    },
    {
        "name": "Devil Costume",
        "category": "costume",
        "description": "Red devil costume with horns, tail, and pitchfork",
        "min_price": 35,
        "max_price": 85,
    },
    
    # Masks
    {
        "name": "Haunted Pumpkin Mask",
        "category": "mask",
        "description": "Terrifying pumpkin mask with glowing eyes and twisted smile",
        "min_price": 20,
        "max_price": 60,
    },
    {
        "name": "Zombie Mask",
        "category": "mask",
        "description": "Detailed zombie mask with rotting flesh and exposed teeth",
        "min_price": 25,
        "max_price": 70,
    },
    {
        "name": "Clown Horror Mask",
        "category": "mask",
        "description": "Creepy clown mask with distorted features and sinister smile",
        "min_price": 25,
        "max_price": 65,
    },
    {
        "name": "Werewolf Mask",
        "category": "mask",
        "description": "Furry werewolf mask with snarling mouth and pointed ears",
        "min_price": 30,
        "max_price": 80,
    },
    {
        "name": "Demon Mask",
        "category": "mask",
        "description": "Demonic mask with horns, red skin, and menacing expression",
        "min_price": 28,
        "max_price": 75,
    },
    {
        "name": "Vintage Ghost Mask",
        "category": "mask",
        "description": "Classic white ghost mask with hollow eyes and mouth",
        "min_price": 15,
        "max_price": 40,
    },
    {
        "name": "Scarecrow Mask",
        "category": "mask",
        "description": "Burlap scarecrow mask with stitched mouth and button eyes",
        "min_price": 22,
        "max_price": 55,
    },
    {
        "name": "Plague Doctor Mask",
        "category": "mask",
        "description": "Long-nosed black plague doctor mask with historical details",
        "min_price": 35,
        "max_price": 90,
    },
    {
        "name": "Alien Mask",
        "category": "mask",
        "description": "Extraterrestrial mask with large eyes and otherworldly features",
        "min_price": 25,
        "max_price": 70,
    },
    {
        "name": "Voodoo Doll Mask",
        "category": "mask",
        "description": "Creepy burlap voodoo doll mask with button eyes and stitched mouth",
        "min_price": 28,
        "max_price": 65,
    },
    
    # Witchy Items
    {
        "name": "Witch's Cauldron",
        "category": "witchy",
        "description": "Large black cauldron for brewing potions, with spooky green mist",
        "min_price": 15,
        "max_price": 45,
    },
    {
        "name": "Crystal Ball",
        "category": "witchy",
        "description": "Mystical crystal ball on ornate stand for fortune telling",
        "min_price": 30,
        "max_price": 80,
    },
    {
        "name": "Witch's Broom",
        "category": "witchy",
        "description": "Traditional witch's broom with twisted wood handle and bound straw",
        "min_price": 15,
        "max_price": 40,
    },
    {
        "name": "Spell Book",
        "category": "witchy",
        "description": "Ancient leather-bound book of spells with mystical symbols",
        "min_price": 25,
        "max_price": 65,
    },
    {
        "name": "Potion Bottles Set",
        "category": "witchy",
        "description": "Collection of glass bottles filled with colorful potions and ingredients",
        "min_price": 20,
        "max_price": 55,
    },
    {
        "name": "Witch's Hat",
        "category": "witchy",
        "description": "Classic pointed black witch hat with buckle and distressed edges",
        "min_price": 12,
        "max_price": 35,
    },
    {
        "name": "Black Cat Familiar",
        "category": "witchy",
        "description": "Lifelike black cat figure with glowing eyes and arched back",
        "min_price": 18,
        "max_price": 50,
    },
    {
        "name": "Tarot Card Deck",
        "category": "witchy",
        "description": "Halloween-themed tarot cards with spooky illustrations",
        "min_price": 15,
        "max_price": 40,
    },
    {
        "name": "Witch's Altar Set",
        "category": "witchy",
        "description": "Complete altar set with candles, chalice, and ritual tools",
        "min_price": 45,
        "max_price": 120,
    },
    {
        "name": "Enchanted Pendulum",
        "category": "witchy",
        "description": "Mystical pendulum for divination with ornate crystal design",
        "min_price": 18,
        "max_price": 45,
    },
    
    # Candy and Treats
    {
        "name": "Assorted Halloween Candy Mix",
        "category": "candy",
        "description": "Mixture of chocolate, gummies, and hard candies with Halloween themes",
        "min_price": 8,
        "max_price": 25,
    },
    {
        "name": "Gourmet Chocolate Eyeballs",
        "category": "candy",
        "description": "Realistic looking chocolate eyeballs filled with caramel",
        "min_price": 12,
        "max_price": 30,
    },
    {
        "name": "Ghost Marshmallows",
        "category": "candy",
        "description": "Fluffy marshmallows shaped like ghosts with chocolate faces",
        "min_price": 7,
        "max_price": 18,
    },
    {
        "name": "Candy Corn",
        "category": "candy",
        "description": "Traditional tri-colored candy corn in Halloween packaging",
        "min_price": 5,
        "max_price": 15,
    },
    {
        "name": "Spider Gummies",
        "category": "candy",
        "description": "Spider-shaped gummy candies in assorted fruity flavors",
        "min_price": 6,
        "max_price": 16,
    },
    {
        "name": "Witch's Brew Popcorn",
        "category": "candy",
        "description": "Green and purple caramel popcorn with candy pieces",
        "min_price": 10,
        "max_price": 25,
    },
    {
        "name": "Mummy Cookie Kit",
        "category": "candy",
        "description": "DIY cookie decorating kit to create mummy-wrapped cookies",
        "min_price": 15,
        "max_price": 35,
    },
    {
        "name": "Blood Red Lollipops",
        "category": "candy",
        "description": "Cherry-flavored lollipops that look like drops of blood",
        "min_price": 8,
        "max_price": 20,
    },
    {
        "name": "Pumpkin Fudge",
        "category": "candy",
        "description": "Creamy pumpkin-spiced fudge cut into pumpkin shapes",
        "min_price": 12,
        "max_price": 28,
    },
    {
        "name": "Monster Bark",
        "category": "candy",
        "description": "Chocolate bark with candy eyes, sprinkles, and Halloween candies",
        "min_price": 14,
        "max_price": 30,
    },
    
    # Decorations
    {
        "name": "Animated Skeleton",
        "category": "decoration",
        "description": "Life-sized skeleton that moves and makes spooky sounds",
        "min_price": 50,
        "max_price": 150,
    },
    {
        "name": "Ghost Hologram Projector",
        "category": "decoration",
        "description": "Projects realistic ghost holograms throughout your home",
        "min_price": 35,
        "max_price": 100,
    },
    {
        "name": "Haunted Tree Face",
        "category": "decoration",
        "description": "Spooky face attachment that brings trees to life with glowing eyes",
        "min_price": 20,
        "max_price": 50,
    },
    {
        "name": "Hanging Bat Colony",
        "category": "decoration",
        "description": "Set of realistic bats that can be hung from ceilings or trees",
        "min_price": 15,
        "max_price": 40,
    },
    {
        "name": "Fog Machine",
        "category": "decoration",
        "description": "Creates eerie fog effects for your Halloween party or haunted house",
        "min_price": 45,
        "max_price": 120,
    },
    {
        "name": "Graveyard Kit",
        "category": "decoration",
        "description": "Complete set of tombstones, zombie hands, and fence pieces",
        "min_price": 30,
        "max_price": 85,
    },
    {
        "name": "Spider Web Set",
        "category": "decoration",
        "description": "Stretchable spider webs with multiple spiders included",
        "min_price": 12,
        "max_price": 30,
    },
    {
        "name": "Flickering Candelabra",
        "category": "decoration",
        "description": "Gothic candelabra with battery-operated flickering candles",
        "min_price": 25,
        "max_price": 60,
    },
    {
        "name": "Animated Doorbell",
        "category": "decoration",
        "description": "Motion-activated doorbell with creepy sounds and glowing eyes",
        "min_price": 20,
        "max_price": 50,
    },
    {
        "name": "Haunted Mirror",
        "category": "decoration",
        "description": "Mirror that shows a ghostly reflection when someone walks by",
        "min_price": 40,
        "max_price": 100,
    },
]
